#!/usr/bin/env bash
# Transfers a file from local client to remote server
if [ "$#" -lt 3 ];
then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
    exit
fi
echo "$1"
scp -i "$4" "$1" "$3"@"$2":~/
