#!/usr/bin/env bash
# Installs and configures NginX on remote server
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
cd /var/www/
sudo chmod -R 777 html
echo 'Hello World!' > html/index.html
sudo chmod -R 755 html
cd ~
sudo nginx -t
sudo service nginx restart
