#!/usr/bin/env bash
# Installs and configures a new HAProxy load balancer
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.6
sudo apt-get -y install haproxy=2.6.\*
sudo chmod 777 /etc/default/haproxy
echo -e '\tENABLED=1' >> /etc/default/haproxy
sudo chmod 644 /etc/default/haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
script=\
"\nfrontend load_balancer
	  bind *:80
	  option forwardfor
	  default_backend web_backend

backend web_backend
	balance roundrobin
	server web-01	54.152.2.54:80	check
	server web-02	3.84.161.121:80	check
"
sudo chmod 777 /etc/haproxy/haproxy.cfg
echo -e "$script" >> /etc/haproxy/haproxy.cfg
sudo chmod 644 /etc/haproxy/haproxy.cfg
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
