#!/usr/bin/env bash
# Installs and configures a new HAProxy load balancer
sudo apt-get -y update
sudo apt-get -y upgrade
sudo apt-get -y install --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-1.8
sudo apt-get -y install haproxy=1.8.\*
sudo chmod 777 /etc/default/haproxy
echo -e '\tENABLED=1' >> /etc/default/haproxy
sudo chmod 644 /etc/default/haproxy
sudo cp -a /etc/haproxy/haproxy.cfg{,.orig}
script=\
"\nfrontend load_balancer
	  bind *:80
	  option forwardfor
	  default_backend web_backend

backend web_backend
	balance roundrobin
	server 43899-web-01	54.152.2.54:80	check
	server 43899-web-02	3.84.161.121:80	check

listen stats
       bind :8800
       stats enable
       stats uri /
       stats hide-version
       stats auth liferesound:liferesound
       default_backend web_backend
"
sudo chmod 777 /etc/haproxy/haproxy.cfg
echo -e "$script" >> /etc/haproxy/haproxy.cfg
sudo chmod 644 /etc/haproxy/haproxy.cfg
sudo haproxy -f /etc/haproxy/haproxy.cfg -c
sudo service haproxy restart
