#!/usr/bin/env bash
# Creates a compressed archive of the mysql database dump back up.
mysqldump --all-databases -uroot -p"$1" -r backup.sql
date=$(date +"%d-%m-%Y")
tar -czvf "$date".tar.gz backup.sql
