#!/usr/bin/env bash
# configures nginx to listen on port 80
config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;

	root /usr/share/nginx/html;
	index index.html index.htm;

	server_name localhost;

	location / {
		 try_files \$uri \$uri/ =404;
	 }
}"
sudo chmod -R 777 /etc/nginx/sites-enabled
echo -e "$config" > /etc/nginx/sites-enabled/default
sudo chmod -R 644 /etc/nginx/sites-enabled
sudo service nginx restart
