#!/usr/bin/env bash
# Configures nginx to run as nginx user
pkill -f apache2
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80 default.*/8080 default_server;/g' /etc/nginx/sites-available/default
#sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 700 /etc/nginx/nginx.conf
sudo -u nginx service nginx start
