#!/usr/bin/env bash
# Configures nginx to run as nginx user
sed -i 's/^#user.*/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80 .*/&\n\tlisten 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:80 .*/&\n\tlisten [::]:8080 default_server ipv6only=on;/' /etc/nginx/sites-available/default
sudo service nginx start
