#!/usr/bin/env bash
# Configures nginx to run as nginx user
pkill -f apache2
sudo chmod 644 /etc/nginx/nginx.conf
sed -i 's/#user www-data/user nginx/g' /etc/nginx/nginx.conf
sed -i 's/80 default.*/8080 default_server;/g' /etc/nginx/sites-available/default
sudo -u nginx service nginx start
