#!/usr/bin/env bash
# Creating a new SSH key pair
# Name of private key must be `school`
# Number of bits in created key must be `4096`
# key must be protected by passphrase `betty`

ssh-keygen -b 4096 -f school -N betty
